name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
  date_now_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Now it is
        run: |
          date
  directory_content_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Directory content
        run: |
          ls -l
